# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
    - "2.7"

addons:
    chrome: stable

before_install:
    - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    - pip install coveralls


install:
    - pip install -r requirements/test.txt

script:
    - flake8 selenium_astride tests
    - coverage run --source selenium_astride setup.py test

after_success:
    - coveralls


